// Reference data (countries → continent, age ranges) — ported from README.md /
// API_AND_SCHEMA.md, expanded to a broader standard country list (includes
// Taiwan + the commonly-used ~170 countries/territories). Mirrors what's
// seeded into the `countries` / `age_ranges` tables (db/seed.sql). Kept here
// too so the client can render selects/labels without a round trip.

export const CONTINENTS = ["Asia", "Europe", "Americas", "Oceania", "Africa"] as const;
export type Continent = (typeof CONTINENTS)[number];

export const COUNTRY_CONTINENT: Record<string, Continent> = {
  "Afghanistan": "Asia",
  "Armenia": "Asia",
  "Azerbaijan": "Asia",
  "Bahrain": "Asia",
  "Bangladesh": "Asia",
  "Bhutan": "Asia",
  "Brunei": "Asia",
  "Cambodia": "Asia",
  "China": "Asia",
  "Cyprus": "Asia",
  "Georgia": "Asia",
  "Hong Kong": "Asia",
  "India": "Asia",
  "Indonesia": "Asia",
  "Iran": "Asia",
  "Iraq": "Asia",
  "Israel": "Asia",
  "Japan": "Asia",
  "Jordan": "Asia",
  "Kazakhstan": "Asia",
  "Kuwait": "Asia",
  "Kyrgyzstan": "Asia",
  "Laos": "Asia",
  "Lebanon": "Asia",
  "Macau": "Asia",
  "Malaysia": "Asia",
  "Maldives": "Asia",
  "Mongolia": "Asia",
  "Myanmar": "Asia",
  "Nepal": "Asia",
  "North Korea": "Asia",
  "Oman": "Asia",
  "Pakistan": "Asia",
  "Palestine": "Asia",
  "Philippines": "Asia",
  "Qatar": "Asia",
  "Saudi Arabia": "Asia",
  "Singapore": "Asia",
  "South Korea": "Asia",
  "Sri Lanka": "Asia",
  "Syria": "Asia",
  "Taiwan": "Asia",
  "Tajikistan": "Asia",
  "Thailand": "Asia",
  "Timor-Leste": "Asia",
  "Turkmenistan": "Asia",
  "UAE": "Asia",
  "Uzbekistan": "Asia",
  "Vietnam": "Asia",
  "Yemen": "Asia",
  "Albania": "Europe",
  "Andorra": "Europe",
  "Austria": "Europe",
  "Belarus": "Europe",
  "Belgium": "Europe",
  "Bosnia and Herzegovina": "Europe",
  "Bulgaria": "Europe",
  "Croatia": "Europe",
  "Czech Republic": "Europe",
  "Denmark": "Europe",
  "Estonia": "Europe",
  "Finland": "Europe",
  "France": "Europe",
  "Germany": "Europe",
  "Greece": "Europe",
  "Hungary": "Europe",
  "Iceland": "Europe",
  "Ireland": "Europe",
  "Italy": "Europe",
  "Kosovo": "Europe",
  "Latvia": "Europe",
  "Liechtenstein": "Europe",
  "Lithuania": "Europe",
  "Luxembourg": "Europe",
  "Malta": "Europe",
  "Moldova": "Europe",
  "Monaco": "Europe",
  "Montenegro": "Europe",
  "Netherlands": "Europe",
  "North Macedonia": "Europe",
  "Norway": "Europe",
  "Poland": "Europe",
  "Portugal": "Europe",
  "Romania": "Europe",
  "Russia": "Europe",
  "San Marino": "Europe",
  "Serbia": "Europe",
  "Slovakia": "Europe",
  "Slovenia": "Europe",
  "Spain": "Europe",
  "Sweden": "Europe",
  "Switzerland": "Europe",
  "Turkey": "Europe",
  "Ukraine": "Europe",
  "UK": "Europe",
  "Vatican City": "Europe",
  "Argentina": "Americas",
  "Bahamas": "Americas",
  "Barbados": "Americas",
  "Belize": "Americas",
  "Bolivia": "Americas",
  "Brazil": "Americas",
  "Canada": "Americas",
  "Chile": "Americas",
  "Colombia": "Americas",
  "Costa Rica": "Americas",
  "Cuba": "Americas",
  "Dominican Republic": "Americas",
  "Ecuador": "Americas",
  "El Salvador": "Americas",
  "Guatemala": "Americas",
  "Guyana": "Americas",
  "Haiti": "Americas",
  "Honduras": "Americas",
  "Jamaica": "Americas",
  "Mexico": "Americas",
  "Nicaragua": "Americas",
  "Panama": "Americas",
  "Paraguay": "Americas",
  "Peru": "Americas",
  "Puerto Rico": "Americas",
  "Suriname": "Americas",
  "Trinidad and Tobago": "Americas",
  "USA": "Americas",
  "Uruguay": "Americas",
  "Venezuela": "Americas",
  "Australia": "Oceania",
  "Fiji": "Oceania",
  "New Zealand": "Oceania",
  "Papua New Guinea": "Oceania",
  "Samoa": "Oceania",
  "Solomon Islands": "Oceania",
  "Tonga": "Oceania",
  "Vanuatu": "Oceania",
  "Algeria": "Africa",
  "Angola": "Africa",
  "Benin": "Africa",
  "Botswana": "Africa",
  "Burkina Faso": "Africa",
  "Cameroon": "Africa",
  "Chad": "Africa",
  "Congo (DRC)": "Africa",
  "Congo (Republic)": "Africa",
  "Cote d'Ivoire": "Africa",
  "Egypt": "Africa",
  "Ethiopia": "Africa",
  "Gabon": "Africa",
  "Ghana": "Africa",
  "Kenya": "Africa",
  "Libya": "Africa",
  "Madagascar": "Africa",
  "Malawi": "Africa",
  "Mali": "Africa",
  "Morocco": "Africa",
  "Mozambique": "Africa",
  "Namibia": "Africa",
  "Niger": "Africa",
  "Nigeria": "Africa",
  "Rwanda": "Africa",
  "Senegal": "Africa",
  "Somalia": "Africa",
  "South Africa": "Africa",
  "Sudan": "Africa",
  "Tanzania": "Africa",
  "Togo": "Africa",
  "Tunisia": "Africa",
  "Uganda": "Africa",
  "Zambia": "Africa",
  "Zimbabwe": "Africa",
};

export const COUNTRY_NAMES: string[] = Object.keys(COUNTRY_CONTINENT).sort();

export const AGE_RANGES: string[] = ["13-17", "18-24", "25-34", "35-44", "45-54", "55-64", "65+"];

// Display form uses an en-dash per the design ("13–17"); API/DB use a plain
// hyphen (matches API_AND_SCHEMA.md examples & is friendlier as a URL/JSON value).
export function ageRangeDisplay(code: string): string {
  return code === "65+" ? "65+" : code.replace("-", "–");
}
